version: "2.0"
services:
  app:
    build:
      args:
        user: simplificado
        uid: 1000
      context: ./
      dockerfile: ./docker/Dockerfile
    image: api
    environment:
      XDEBUG_CONFIG: remote_host=172.19.0.4
      PHP_IDE_CONFIG: "serverName=xdebug-docker"
    container_name: simplificado
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - api
  db:
    image: postgres:12
    container_name: api-db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=simplificado
      - POSTGRES_USER=simplificado
      - POSTGRES_PASSWORD=passwordSimplificado
    volumes:
      - ./docker/postgres/:/var/lib/postgresql/data
    networks:
      - api

  nginx:
    image: nginx:1.17-alpine
    container_name: api-nginx
    restart: unless-stopped
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./docker/nginx/:/etc/nginx/conf.d
    networks:
      - api

networks:
  api:
    driver: bridge
